app.cors.allowed-origins=${CORS_ALLOWED_ORIGIN:https://echoapp.site}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
logging.level.root=WARN
logging.level.com.example.echo=INFO
server.ssl.enabled=${SERVER_SSL_ENABLED:false}
server.ssl.key-store=${SSL_KEYSTORE_PATH:}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:}